---
- name: check mysql repository
  command: ls -l /etc/yum.repos.d/mysql-community.repo
  ignore_errors: true
  register: chkMySQLRepo
  tags:
    - mysql

- name: Install mysql repository
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present
  when: chkMySQLRepo|failed
  tags:
    - mysql

- name: install mysql5.7 client
  yum: name=mysql-community-client state=present enablerepo=mysql57-community*
  tags:
    - mysql